export interface SubProperty {
  name: string;
  desc: string;
}

export interface Project {
  slug: string;
  client: string;
  sector: string;
  years: string;
  title: string;
  desc: string;
  body?: string;
  scope: string[];
  impact: string;
  color?: string;
  logo?: string;
  logoDark?: boolean;
  properties?: SubProperty[];
}

export const projects: Project[] = [
  {
    slug: "national-minorities-day",
    client: "Executive Office of the President – Kenya",
    sector: "Government & Public Institutions",
    years: "2024–2026",
    title: "National Minorities Day",
    desc: "Creative and communications agency for Kenya's flagship national observance led by the Executive Office of the President. Delivered with the sensitivity that high-level government mandates demand — while achieving measurable national media impact.",
    scope: [
      "Creative direction and theme development",
      "Event branding and identity systems",
      "Fabrication and on-ground installation",
      "Media booking and buying",
      "Public relations strategy and execution",
      "Influencer marketing and digital amplification",
      "Stakeholder visibility and national media coverage",
    ],
    impact: "High-level government communication delivered with sensitivity, accuracy and national impact.",
    color: "#750006",
    logo: "/logos/executive-office-president.png",
  },
  {
    slug: "africa-urban-forum-2026",
    client: "Africa Urban Forum (AUF) 2026",
    sector: "Government & Public Institutions",
    years: "2026",
    title: "Continental Urban Development Forum",
    desc: "On-ground experience delivery for the Africa Urban Forum — a high-level continental convening involving the African Union and Kenya's State Department for Housing and Urban Development. Managed a multi-stakeholder environment demanding precision logistics and media coordination.",
    body: "The Africa Urban Forum brought together heads of state, ministers, urban planners, development finance institutions and civil society from across the continent to shape the future of African cities. FID & Co. was entrusted with audience experience coordination within this high-pressure, high-visibility environment — ensuring every delegate interaction, media moment and logistics touchpoint reflected the gravity of the convening.",
    scope: [
      "Audience experience coordination",
      "Event support within a high-level multi-stakeholder environment",
      "Stakeholder and media engagement",
    ],
    impact: "Advanced dialogue around urban development, sustainable cities and infrastructure, and the future of African urban spaces.",
    color: "#D98038",
    logo: "/logos/auf.png",
  },
  {
    slug: "utamaduni-day",
    client: "State Department for Culture, Arts & Heritage",
    sector: "Government & Public Institutions",
    years: "2024",
    title: "Utamaduni Day",
    desc: "Led creative direction, marketing strategy and media engagement for Utamaduni Day 2024 — Kenya's national celebration of cultural heritage. From concept through to broadcast, every element was crafted to honour the country's diverse traditions.",
    scope: [
      "Creative concept development",
      "Branding and visual assets",
      "Social media content and amplification",
      "Road shows",
      "Media booking, PR coverage and interviews",
      "TV commercials, print advertising and event visibility",
    ],
    impact: "Supported national cultural celebration and storytelling, reinforcing Kenya's diverse heritage across media platforms.",
    color: "#D9AB88",
    logo: "/logos/state-dept-culture.png",
  },
  {
    slug: "lc-waikiki-africa",
    client: "LC Waikiki Sub-Saharan Africa",
    sector: "Retail & Fashion",
    years: "2024–2026",
    title: "Digital & Communications Agency",
    desc: "Official digital and communications agency for LC Waikiki Africa across multiple Sub-Saharan markets. Delivering locally resonant storytelling while maintaining global brand alignment — simultaneously managing Kenya, Uganda and Zambia.",
    body: "FID & Co. served as the official digital and communications agency for LC Waikiki Africa, supporting the brand across multiple Sub-Saharan markets. Our mandate focused on delivering locally relevant yet globally aligned storytelling, ensuring consistency with global brand standards while adapting to diverse African audiences. As part of our digital delivery, FID & Co. integrated AI into content production to scale creative output across markets — developing AI-generated muses and virtual models to showcase collections across multiple African audiences, enabling faster turnarounds, cost-efficient production and future-ready fashion storytelling.",
    scope: [
      "Digital content strategy and creation",
      "Social media management across markets",
      "Influencer identification and engagement",
      "Campaign execution and reporting",
      "Internal communications videos for Kenya, Uganda and Zambia",
      "Padel sponsorship activation",
      "AI-integrated digital production and virtual model campaigns",
    ],
    impact: "Delivered scaled creative output across multiple African markets while maintaining brand consistency and global alignment.",
    color: "#750006",
    logo: "/logos/lc-waikiki.png",
  },
  {
    slug: "kansai-plascon",
    client: "Kansai Plascon Paints Kenya",
    sector: "Manufacturing & Corporate Brands",
    years: "2025–2026",
    title: "Gor Mahia Partnership & Communications Partner",
    desc: "Led communications for the landmark Gor Mahia partnership launch and appointed Official Communications Partner for Kansai Plascon Paints Kenya. Built the brand's narrative around communities, craft and colour.",
    body: "Kansai Plascon's partnership with Gor Mahia — one of Kenya's most iconic football clubs — was more than a sponsorship. It was a cultural statement. FID & Co. architected the communications strategy around this landmark moment, translating the brand's commitment to colour, community and craft into earned media, digital content and live activation. As the Official Communications Partner, we continue to shape Plascon's narrative presence across corporate and consumer touchpoints.",
    scope: [
      "Strategic communications planning",
      "Brand narrative and messaging refinement",
      "Production events curation",
      "Media relations and corporate storytelling",
      "Influencer and content strategy",
      "Stakeholder and partner communications",
    ],
    impact: "Positioned Kansai Plascon as a market leader shaping spaces, communities and lifestyles across Kenya.",
    color: "#D98038",
    logo: "/logos/kansai-plascon.png",
  },
  {
    slug: "thrive-hospitality-group",
    client: "Thrive Hospitality Group",
    sector: "Hospitality, Lifestyle & Destination Brands",
    years: "Ongoing",
    title: "Brand Launches & Repositioning",
    desc: "Communications partner across the full Thrive Hospitality Group portfolio — Café NBO, Glam Hotel, Social 8, Chaii Republic and Kingfisher Nest Hotel. Each property required its own distinct voice, audience and launch strategy.",
    body: "FID & Co. has worked closely with Thrive Hospitality Group across multiple properties, supporting brand launches, repositioning, experiential activations and ongoing communications. Our role has been to ensure each property launches and operates not just as a venue, but as a distinct lifestyle destination with a clear audience, story and visual identity.",
    scope: [
      "Brand positioning and launch strategy",
      "Influencer and creator engagement (IG & TikTok)",
      "Media hosting and lifestyle PR",
      "Experiential event design and execution",
      "Content strategy for digital platforms",
      "On-ground event production and coordination",
    ],
    impact: "Each property launched as a distinct lifestyle destination with a clear audience, story and visual identity.",
    color: "#D9AB88",
    logo: "/logos/thrive-hospitality.png",
    properties: [
      {
        name: "Café NBO",
        desc: "Supported brand launch and visibility through curated influencer experiences, media engagement and digital storytelling, positioning Café NBO as a contemporary, urban café concept.",
      },
      {
        name: "Glam Hotel – Westlands",
        desc: "Led rooftop launch events, influencer hosting and lifestyle media engagement, positioning Glam Hotel as a premium lifestyle and nightlife destination in Westlands.",
      },
      {
        name: "Social 8",
        desc: "Supported ongoing brand experiences, influencer activations and content amplification, reinforcing Social 8's positioning as a social dining and lifestyle space.",
      },
      {
        name: "Chaii Republic",
        desc: "Delivered concept launch support, influencer engagement and experiential storytelling to introduce Chaii Republic as a modern tea and social culture brand.",
      },
      {
        name: "Kingfisher Nest Hotel",
        desc: "Led launch activations, media hosting and experiential curation, supporting the hotel's entry into Nairobi's hospitality market with strong visibility and brand recall.",
      },
    ],
  },
  {
    slug: "africa-forum-on-displacements",
    client: "The Amahoro Coalition & UNHCR",
    sector: "Social Impact & Multilateral Partnerships",
    years: "2023",
    title: "Africa Forum on Displacements — Accra, Ghana",
    desc: "Communications and media engagement for the Private Sector Forum on Displaced Persons held during the Africa Forum on Displacements, Accra. Coordinated multilateral media access across multiple African markets.",
    body: "In 2023, FID & Co. partnered with The Amahoro Coalition and UNHCR to support communications and media engagement for the Private Sector Forum on Displaced Persons, held during the Africa Forum on Displacements in Accra, Ghana. This high-level forum brought together governments, private sector leaders, development partners and humanitarian organisations to advance dialogue on private-sector solutions for displaced populations across Africa. FID & Co.'s role was to ensure the forum achieved continental visibility, narrative clarity and stakeholder resonance — particularly around the role of business in supporting refugee livelihoods and inclusive growth. The engagement reflects our capability to operate within complex, multi-stakeholder environments, balancing institutional messaging, donor sensitivities and public interest.",
    scope: [
      "Strategic communications support for the forum",
      "Media engagement and interview coordination across multiple African markets",
      "Development of key messaging",
      "Coordination of spokesperson interviews with regional and international media",
      "Amplification of forum outcomes through earned media coverage",
    ],
    impact: "Elevated conversations around private-sector leadership and sustainable solutions for displaced persons across Africa.",
    color: "#750006",
    logo: "/logos/unhcr.png",
  },
  {
    slug: "columbia-africa-healthcare",
    client: "Columbia Africa Healthcare",
    sector: "Healthcare & Medical Institutions",
    years: "2025",
    title: "Strategic Communications & Internal Alignment",
    desc: "Strategic communications and internal alignment across healthcare facilities for one of Kenya's leading networks of hospitals and clinics. Built visual stories that reinforce institutional trust and care standards.",
    body: "FID & Co. worked with Columbia Africa Healthcare Ltd to support strategic communications and internal alignment across its healthcare facilities. Our engagement focused on strengthening how the organisation communicates its services, expertise and patient-centred approach to both internal stakeholders and the wider public. By translating complex healthcare services into clear, accessible and reassuring narratives, FID & Co. supported Columbia Africa in enhancing stakeholder confidence and reinforcing its reputation as a trusted healthcare provider. This work demonstrates our ability to operate effectively within highly regulated, sensitive sectors where accuracy, tone and credibility are critical.",
    scope: [
      "Internal communications video profiles for hospitals and clinics",
      "Digital display content for healthcare facilities",
      "Visual storytelling highlighting medical services, facilities and care standards",
    ],
    impact: "Enhanced stakeholder confidence and reinforced Columbia Africa's reputation as a trusted healthcare provider.",
    color: "#D98038",
    logo: "/logos/columbia-africa.png",
  },
  {
    slug: "allso-beauty",
    client: "Allso Beauty",
    sector: "Beauty, Wellness & Lifestyle",
    years: "2024",
    title: "Brand Launch & Experiential Campaign",
    desc: "FID & Co. led the brand launch and experiential campaign for Allso Beauty, introducing the cosmetics brand to the Kenyan market through a curated beauty and influencer experience.",
    body: "Our role focused on creating a launch moment that combined experiential storytelling, influencer engagement and digital amplification, positioning Allso Beauty within the contemporary beauty and lifestyle space. The launch brought together beauty creators, media and lifestyle influencers, generating strong digital engagement while introducing Allso Beauty to a style-conscious audience.",
    scope: [
      "Launch event concept and experiential design",
      "Influencer and beauty creator engagement",
      "Media invitations and lifestyle PR support",
      "Content creation and social media amplification",
      "Brand storytelling through creator-led content",
    ],
    impact: "Successfully introduced Allso Beauty to Kenya's style-conscious audience through a launch moment that drove strong digital engagement and media coverage.",
    color: "#D9AB88",
    logo: "/logos/allso-beauty.png",
  },
  {
    slug: "abyan-salon",
    client: "Abyan Salon & Spa",
    sector: "Beauty, Wellness & Lifestyle",
    years: "2023–2024",
    title: "Brand Revitalisation",
    desc: "Brand revitalisation including rebranding, website development, content strategy and digital campaigns, repositioning Abyan as a leading beauty destination.",
    scope: [
      "Brand strategy and rebranding",
      "Website design and development",
      "Content strategy and production",
      "Digital campaign execution",
      "Photography direction and visual identity refresh",
      "Social media management and community building",
    ],
    impact: "Repositioned Abyan Salon & Spa as a leading beauty destination, with a refreshed visual identity and digital presence to match.",
    color: "#750006",
    logo: "/logos/abyan-salon-spa.png",
  },
  {
    slug: "bomas-of-kenya",
    client: "Bomas of Kenya Ltd",
    sector: "Government & Public Institutions",
    years: "2024",
    title: "Digital Repositioning & Cultural Storytelling",
    desc: "Partnered with Bomas of Kenya to reposition the brand's digital presence and public perception — transforming a traditional tourist destination into a vibrant cultural and lifestyle hub for local audiences.",
    scope: [
      "Strategic content development",
      "Digital storytelling and platform strategy",
      "Public perception repositioning",
      "Domestic audience engagement",
    ],
    impact: "Transformed Bomas from a traditional tourist destination into a vibrant cultural and lifestyle hub, strengthening domestic engagement and relevance.",
    color: "#D9AB88",
    logo: "/logos/bomas-of-kenya.png",
  },
  {
    slug: "woolworths-kenya",
    client: "Woolworths Kenya",
    sector: "Retail & Fashion",
    years: "Ongoing",
    title: "Influencer & Digital Engagement",
    desc: "Ongoing influencer engagement and digital campaign amplification, connecting Woolworths with modern, style-conscious consumers across social platforms.",
    body: "FID & Co. supports Woolworths Kenya through ongoing influencer engagement and digital campaign amplification. Our role involves identifying and curating relevant lifestyle, fashion and retail creators, coordinating influencer collaborations and supporting campaign rollouts aligned with Woolworths' brand positioning and seasonal retail initiatives.",
    scope: [
      "Lifestyle, fashion and retail creator curation",
      "Influencer collaboration coordination",
      "Seasonal campaign rollout support",
      "Coordinated content storytelling",
    ],
    impact: "Consistent digital visibility, authentic audience engagement and sustained brand relevance within Kenya's competitive retail landscape.",
    color: "#1c1c1c",
  },
  {
    slug: "2nu-boutique",
    client: "2nu Boutique",
    sector: "Retail & Fashion",
    years: "Ongoing",
    title: "Fashion Brand Positioning & Content",
    desc: "Partnership with a premium womenswear fashion brand covering brand positioning, fashion content production, influencer collaborations and campaign storytelling.",
    scope: [
      "Brand positioning",
      "Fashion content production",
      "Influencer collaborations",
      "Campaign storytelling",
    ],
    impact: "Reinforced 2nu Boutique's presence within Kenya's contemporary fashion retail space.",
    color: "#750006",
    logo: "/logos/2nu-kollexion.png",
  },
  {
    slug: "chloride-exide",
    client: "Chloride Exide (via Wano Communications)",
    sector: "Manufacturing & Corporate Brands",
    years: "Ongoing",
    title: "Regional Communications — Kenya, Uganda, Rwanda & Ethiopia",
    desc: "As Kenya Affiliate Agency and Country Representative for Wano Communications (South Africa), FID & Co. supports Chloride Exide across four East African markets with local expertise and on-ground execution.",
    scope: [
      "Local market expertise across Kenya, Uganda, Rwanda & Ethiopia",
      "Execution support",
      "Stakeholder engagement",
      "Regional portfolio management",
    ],
    impact: "Regionally aligned, locally executed communications bridging Southern and East African markets.",
    color: "#D98038",
    logo: "/logos/chloride-exide.png",
  },
  {
    slug: "wrc-safari-rally",
    client: "WRC Safari Rally",
    sector: "Sports, Tourism & Mass-Audience Platforms",
    years: "2022",
    title: "Corporate Sponsorship Breakfast",
    desc: "Strategic communications and event support for the WRC Safari Rally Corporate Sponsorship Breakfast — mobilising corporate support ahead of the global motorsport event.",
    scope: [
      "Identification and curation of potential corporate sponsors",
      "Strategic guest list development (150+ CEOs and decision-makers)",
      "Event positioning and stakeholder engagement",
      "Media support and visibility",
    ],
    impact: "A critical platform for mobilising corporate support, reinforcing Kenya's position on the international rally calendar.",
    color: "#750006",
    logo: "/logos/wrc-safari-rally.svg",
    logoDark: true,
  },
  {
    slug: "gor-mahia-launch",
    client: "Gor Mahia Football Club",
    sector: "Sports, Tourism & Mass-Audience Platforms",
    years: "2025",
    title: "Brand & Launch Communications",
    desc: "Supported the Kansai Plascon Kenya x Gor Mahia FC brand partnership launch — strategic communications, media coordination and launch amplification for one of Kenya's most iconic sporting institutions.",
    scope: [
      "Strategic communications support",
      "Media coordination",
      "Launch amplification",
    ],
    impact: "Strong national visibility while maintaining brand integrity for one of Kenya's most iconic sporting institutions.",
    color: "#1f6b4a",
    logo: "/logos/gor-mahia.png",
  },
  {
    slug: "gertrudes-foundation",
    client: "Gertrude's Children's Hospital Foundation",
    sector: "Healthcare & Medical Institutions",
    years: "Ongoing",
    title: "Healthcare Storytelling & Community Impact",
    desc: "Strategic content and storytelling initiatives highlighting healthcare access, community impact and child-centered medical outreach programmes.",
    body: "The collaboration focuses on documenting and amplifying initiatives including mobile medical outreach programmes, telemedicine and digital healthcare access, beneficiary impact stories and community-centered healthcare initiatives. Through visual storytelling and strategic communications support, FID & Co. helps translate healthcare impact into narratives that are accessible, human-centered and engaging.",
    scope: [
      "Mobile medical outreach documentation",
      "Telemedicine and digital healthcare access storytelling",
      "Beneficiary impact stories",
      "Community-centered healthcare initiatives",
    ],
    impact: "Healthcare impact translated into accessible, human-centered narratives for stakeholders, partners and the wider public.",
    color: "#2f6f8f",
    logo: "/logos/gertrudes.png",
  },
  {
    slug: "elysium-capital",
    client: "Elysium Capital Partners Ltd",
    sector: "Finance, Investment & Advisory",
    years: "Ongoing",
    title: "Strategic Communications & Advisory — South Sudan",
    desc: "Strategic communications and advisory partner to a Juba-based investment firm operating across emerging and frontier markets — clarifying complex investment narratives for investors, partners and institutions.",
    scope: [
      "Investor-facing proposals and pitch documentation",
      "Strategic messaging and narrative structuring",
      "Stakeholder communication frameworks",
      "Advisory support on emerging-market positioning",
      "Presentation material refinement",
    ],
    impact: "Investment propositions communicated with rigor, transparency and strategic alignment in complex frontier markets.",
    color: "#1c1c1c",
    logo: "/logos/elysium-capital.png",
  },
  {
    slug: "medigah-london-hair",
    client: "Medigah London Hair",
    sector: "Beauty, Wellness & Lifestyle",
    years: "2024",
    title: "MLH App Launch & Brand Experience",
    desc: "Communications, experiential launch and influencer engagement for a luxury hair and beauty brand introducing its MLH mobile application to the Kenyan market — at the intersection of beauty, fashion and technology.",
    body: "Hosted at The Social House Hotel in Nairobi, the high-profile launch brought together media personalities, beauty creators, fashion influencers and lifestyle tastemakers to celebrate the debut of the MLH App and its luxury product range. FID & Co. was responsible for shaping the launch moment and ensuring strong visibility across media and digital platforms.",
    scope: [
      "Launch event concept and experiential design",
      "Strategic communications and PR support",
      "Media engagement and press coordination",
      "Influencer and beauty creator management",
      "Lifestyle and entertainment programming",
      "Digital content capture and amplification",
    ],
    impact: "Strong digital attention, positioning Medigah London Hair as a premium beauty brand entering the East African market.",
    color: "#b5397a",
    logo: "/logos/medigah-london-hair.png",
  },
  {
    slug: "luxury-body-spa",
    client: "Luxury Body Spa",
    sector: "Beauty, Wellness & Lifestyle",
    years: "2023",
    title: "Brand Identity Refresh",
    desc: "Brand identity refresh, premium collateral development and PR support, enhancing brand perception and visibility.",
    scope: [
      "Brand identity refresh",
      "Premium collateral development",
      "PR support",
    ],
    impact: "Enhanced brand perception and visibility within Nairobi's wellness space.",
    color: "#D9AB88",
  },
  {
    slug: "rukybeau",
    client: "RukyBeau Makeup Artistry",
    sector: "Beauty, Wellness & Lifestyle",
    years: "Ongoing",
    title: "Personal Brand Positioning",
    desc: "Brand positioning, visual storytelling and digital visibility for a professional makeup artistry brand — strengthening personal brand authority and audience engagement.",
    scope: [
      "Brand positioning",
      "Visual storytelling",
      "Digital visibility strategy",
    ],
    impact: "Strengthened personal brand authority and audience engagement.",
    color: "#750006",
  },
  {
    slug: "talanta-afrika",
    client: "Talanta Afrika Festival",
    sector: "Culture, Entertainment & Experiential Platforms",
    years: "Ongoing",
    title: "Regional PR, Media & Influencer Strategy",
    desc: "Regional public relations, media and influencer management for a cross-border cultural platform celebrating African music, fashion, cuisine and creative expression across Kenya, Uganda and Rwanda.",
    scope: [
      "Regional PR strategy and media relations",
      "Media booking and buying across three markets",
      "Influencer and creator engagement across Kenya, Uganda and Rwanda",
      "Press conference coordination and media hosting",
      "Campaign messaging, digital amplification and content visibility",
    ],
    impact: "Strong regional awareness supporting the festival's growth as a multi-country cultural platform.",
    color: "#8a5cf0",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
