export interface PressArticle {
  title: string;
  url: string;
  source: string;
  image: string;
  campaign: string;
  campaignSlug: string;
  sector: string;
}

export const CAMPAIGNS = [
  { slug: "chaii-republic", name: "The Chaii Republic Launch", sector: "Hospitality" },
  { slug: "cafe-nbo", name: "Café NBO Opening", sector: "Hospitality" },
  { slug: "glam-hotel", name: "Glam Hotel Rooftop Launch", sector: "Hospitality" },
  { slug: "the-perch", name: "The Perch Reopening", sector: "Hospitality" },
  { slug: "suhba-series", name: "Suhba Series — Mother's Day", sector: "Owned IPs" },
  { slug: "allso-beauty", name: "Allso Beauty Launch", sector: "Beauty, Wellness & Lifestyle" },
] as const;

export const pressArticles: PressArticle[] = [
  { title: "The Chaii Republic launches in Nairobi", url: "https://www.citizen.digital/news/the-chaii-republic-launches-in-nairobi-n365678", source: "Citizen Digital", image: "https://assets.citizen.digital/155224/conversions/WhatsApp-Image-2025-07-06-at-14.06.35-og_image.webp", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Good cup: Chai culture meets Kenyan coffee culture as Chaii Republic launches", url: "https://www.tuko.co.ke/business-economy/595331-chai-culture-meets-kenyan-coffee-culture-chaii-republic-launches/", source: "Tuko", image: "https://cdn.tuko.co.ke/images/1200x675/33f4d28bf79ed8b1.jpeg?v=1", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Chaii Republic Launches in Nairobi, Blending India's Iconic Chai Culture with Kenyan Coffee Sophistication - TouchLineNews", url: "https://touchlinenews.com/chaii-republic-launches-in-nairobi-blending-indias-iconic-chai-culture-with-kenyan-coffee-sophistication/", source: "Touchline News", image: "https://touchlinenews.com/wp-content/uploads/2025/07/IMG-20250707-WA0024-scaled.jpg", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Chai Meets Coffee: The Chaii Republic Brews a New Blend in Nairobi", url: "https://thetimes.co.ke/chai-meets-coffee-the-chaii-republic-brews-a-new-blend-in-nairobipp/", source: "The Times Kenya", image: "https://thetimes.co.ke/wp-content/uploads/2025/07/IMG-20250707-WA0025-scaled-1.jpg", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Nairobi Gets a Taste of India as The Chaii Republic Launches in Westlands - ynews.digital", url: "https://ynews.digital/newsflash/nairobi-gets-a-taste-of-india-as-the-chaii-republic-launches-in-westlands/", source: "Y News", image: "https://ynews.digital/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-06-at-9.29.37-AM-scaled.jpeg", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Chaii Republic Launches in Nairobi, Blending India's Iconic Chai Culture with Kenyan Coffee Sophistication", url: "https://www.capitalfm.co.ke/news/2025/07/chaii-republic-launches-in-nairobi-blending-indias-iconic-chai-culture-with-kenyan-coffee-sophistication/", source: "Capital FM", image: "https://capitalfm.africa/wp-content/uploads/news/2025/07/WhatsApp-Image-2025-07-06-at-1.21.48-PM-scaled.jpeg", campaign: "The Chaii Republic Launch", campaignSlug: "chaii-republic", sector: "Hospitality" },
  { title: "Chaii Republic Unveils Café NBO, Its New Cultural Tea Hub in Nairobi - TouchLineNews", url: "https://touchlinenews.com/chaii-republic-unveils-cafe-nbo-its-new-cultural-tea-hub-in-nairobi/", source: "Touchline News", image: "https://touchlinenews.com/wp-content/uploads/2025/09/IMG-20250906-WA0004.jpg", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Chaii Republic Opens Café NBO in Nairobi, Its New Cultural Tea and Food Hub - ynews.digital", url: "https://ynews.digital/business/chaii-republic-opens-cafe-nbo-in-nairobi-its-new-cultural-tea-and-food-hub/", source: "Y News", image: "https://ynews.digital/wp-content/uploads/2025/09/image-5-1024x682.png", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Tea and culture: Chaii Republic launches Café NBO in Nairobi", url: "https://www.tuko.co.ke/business-economy/602192-chaii-republic-launches-cafe-nbo-nairobi-blends-tea-culture-creativity/", source: "Tuko", image: "https://cdn.tuko.co.ke/images/1200x675/926b89288718fc00.jpeg?v=1", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Chaii Republic unveils cultural tea hub in Nairobi", url: "https://www.standardmedia.co.ke/business/enterprise/article/2001528799/chaii-republic-unveils-cultural-tea-hub-in-nairobi", source: "The Standard", image: "https://cdn.standardmedia.co.ke/images/articles/thumbnails/dZa0h8IhkfTE0SjfdgNikU5C9M5gmZ5ocVrJ4NL6.jpg", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Chaii Republic Unveils Café NBO, Its New Cultural Tea Hub in Nairobi", url: "https://www.capitalfm.co.ke/news/2025/09/chaii-republic-unveils-cafe-nbo-its-new-cultural-tea-hub-in-nairobi/", source: "Capital FM", image: "https://capitalfm.africa/wp-content/uploads/news/2025/09/IMG-20250906-WA0038-scaled.jpg", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Glam Hotel Opens Stylish Rooftop Restaurant in Westlands", url: "https://thetimes.co.ke/glam-hotel-opens-stylish-rooftop-restaurant-in-westlands/", source: "The Times Kenya", image: "https://magictouchmedia.co.ke/wp-content/uploads/2025/11/49421a33-ec63-4030-ad98-c7ef04c08403-300x200.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel Opens New Rooftop Restaurant and Bar in Nairobi - ynews.digital", url: "https://ynews.digital/top-stories/glam-hotel-opens-new-rooftop-restaurant-and-bar-in-nairobi/", source: "Y News", image: "https://ynews.digital/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-09-at-10.56.30-1.jpeg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Sky High Glamour: Inside the Launch of Glam Hotel's Stunning Rooftop Restaurant and Bar", url: "https://www.mpasho.co.ke/lifestyle-yetu/2025-11-09-inside-the-launch-of-glam-hotels-stunning-rooftop-restaurant-and-bar", source: "Mpasho", image: "https://cdn.radioafrica.digital/image/2025/11/03f078f8-4472-43cb-b3a9-21fdb558228a.jpg?1783929793218", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel Opens New Rooftop Restaurant and Bar in Nairobi", url: "https://www.capitalfm.co.ke/news/2025/11/glam-hotel-opens-new-rooftop-restaurant-and-bar-in-nairobi/", source: "Capital FM", image: "https://capitalfm.africa/wp-content/uploads/news/2025/11/IMG-20251110-WA00001-scaled.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel unveils new rooftop restaurant and bar, bringing luxury dining to Nairobi's skyline - News 9", url: "https://www.news9.africa/business/glam-hotel-unveils-new-rooftop-restaurant-and-bar-bringing-luxury-dining-to-nairobis-skyline-9845/", source: "News9 Africa", image: "https://www.news9.africa/wp-content/uploads/2025/11/Glam.webp", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Patrons to Feel Nairobi's Touch As Glam Hotel Opens New Rooftop Restaurant and Bar", url: "https://kenyaonlinenews.com//patrons-to-feel-nairobi-s-touch-as-glam-hotel-opens-new-rooftop-restaurant-and-bar", source: "Kenya Online News", image: "https://res.cloudinary.com/dqpbmvmt5/image/upload/v1762773406/articles/elpju6agajfudfj7ynvs.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Patrons to Feel Nairobi's Touch as Glam Hotel Opens New Rooftop Restaurant and Bar", url: "https://nipashebiz.co.ke/patrons-to-feel-nairobis-touch-as-glam-hotel-opens-new-rooftop-restaurant-and-bar/", source: "Nipashe Biz", image: "https://nipashebiz.co.ke/wp-content/uploads/2025/11/IMG-20251110-WA0035.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel Launches Elegant Rooftop Restaurant and Bar in Westlands, Nairobi", url: "https://ghettoradio.co.ke/glam-hotel-launches-elegant-rooftop-restaurant-and-bar-in-westlands-nairobi/", source: "Ghetto Radio", image: "https://ghettoradio.co.ke/wp-content/uploads/2025/11/IMG-20251110-WA0049.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel Unveils Chic Rooftop Restaurant and Bar in Nairobi's Westlands", url: "https://hivisasanews.co.ke/glam-hotel-unveils-chic-rooftop-restaurant-and-bar-in-nairobis-westlands/", source: "Hivisasa", image: "https://hivisasanews.co.ke/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-10-at-19.33.30_f2228fab.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "A New Peak: Glam Hotel Elevates Nairobi&#8217;s Dining Scene with Vibrant Rooftop Bar - Spot Light Justice", url: "https://spotlightjustice.co.ke/latest-news/a-new-peak-glam-hotel-elevates-nairobis-dining-scene-with-vibrant-rooftop-bar/3167/", source: "Spotlight Justice", image: "https://spotlightjustice.co.ke/wp-content/uploads/2025/11/IMG-20251110-WA0010.jpg", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Nairobi's The Perch Reopens at Kingfisher Nest Hotel After Major Renovation - ynews.digital", url: "https://ynews.digital/entertainment/events/nairobis-the-perch-reopens-at-kingfisher-nest-hotel-after-major-renovation/", source: "Y News", image: "https://ynews.digital/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-25-at-11.37.38-AM.jpeg", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "Perch Restaurant Reopens in Nairobi with New Menu and Skyline Views", url: "https://www.capitalfm.co.ke/news/2025/07/perch-restaurant-reopens-in-nairobi-with-new-menu-and-skyline-views/", source: "Capital FM", image: "https://capitalfm.africa/wp-content/uploads/news/2025/07/WhatsApp-Image-2025-07-25-at-12.53.31-PM-scaled.jpeg", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "The Perch Restaurant Reopens at Kingfisher Nest Hotel, Setting New Standard for Nairobi Dining - TouchLineNews", url: "https://touchlinenews.com/the-perch-restaurant-reopens-at-kingfisher-nest-hotel-setting-new-standard-for-nairobi-dining/", source: "Touchline News", image: "https://touchlinenews.com/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-25-at-14.27.43.jpeg", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "New look: Nairobi hotel closed for over 2 years gets new face, reopens", url: "https://www.tuko.co.ke/business-economy/597349-nairobis-hotel-reopens-2-years-renovation-multi-functional-venue/", source: "Tuko", image: "https://cdn.tuko.co.ke/images/1200x675/2f5a975fdb2cc90d.jpeg?v=1", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "Good news as The Perch reopens at Kingfisher Nest Hotel", url: "https://mulembe.co.ke/2025/07/25/good-news-as-the-perch-reopens-at-kingfisher-nest-hotel/", source: "Mulembe", image: "https://mulembe.co.ke/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-25-at-2.27.42-PM-1.jpeg", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "The Perch Restaurant Reopens At Kingfisher Nest Hotel After Renovations", url: "https://nairobinews.co.ke/the-perch-restaurant-reopens-at-kingfisher-nest-hotel-after-renovations/", source: "Nairobi News", image: "https://nairobinews.co.ke/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-26-at-12.58.13_56c0db85.jpg", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "The Perch Restaurant Reopens At Kingfisher Nest Hotel After Renovations", url: "https://eaglenewsfeed.com/the-perch-restaurant-reopens-at-kingfisher-nest-hotel-after-renovations/", source: "Eagle News Feed", image: "https://eaglenewsfeed.com/wp-content/uploads/2025/07/Screenshot-2025-07-26-152005-1092x800.png", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "Inside the Elegant Rebirth of The Perch Restaurant at Kingfisher Nest Hotel", url: "https://www.mpasho.co.ke/lifestyle-yetu/2025-07-30-inside-the-elegant-rebirth-of-the-perch-restaurant-at-kingfisher-nest-hotel", source: "Mpasho", image: "https://cdn.radioafrica.digital/image/2025/07/4b9ed25d-79d2-4a6c-8d42-5107ffa0ddc0.jpeg?1783929799968", campaign: "The Perch Reopening", campaignSlug: "the-perch", sector: "Hospitality" },
  { title: "Mother&#039;s Day: Suhba Series opens conversations on financial literacy, womanhood", url: "https://www.tnx.africa/events/article/2001547476/mothers-day-suhba-series-opens-conversations-on-financial-literacy-womanhood", source: "TNX Africa", image: "https://cdn.standardmedia.co.ke/images/articles/thumbnails/D9IhYaGKeBPjVxfAFiBVdrW6F3nA55yEu4fRUKwQ.png", campaign: "Suhba Series — Mother's Day", campaignSlug: "suhba-series", sector: "Owned IPs" },
  { title: "Nairobi women mark Mother's Day through faith, finance and sisterhood at sold-out Suhba series debut", url: "https://www.the-star.co.ke/sasa/society/2026-05-10-nairobi-women-mark-mothers-day-through-faith-finance-and-sisterhood-at-sold-out-suhba-series-debut", source: "The Star", image: "https://cdn.radioafrica.digital/image/2026/05/93c6d263-c4bf-4f66-b51d-05d052beb526.jpeg?1783929803946", campaign: "Suhba Series — Mother's Day", campaignSlug: "suhba-series", sector: "Owned IPs" },
  { title: "Nairobi women mark Mother's Day through faith, finance and sisterhood at sold-out Suhba Series debut", url: "https://www.tuko.co.ke/kenya/counties/625784-nairobi-women-mark-mothers-day-faith-finance-sisterhood-sold-suhba-series-debut/", source: "Tuko", image: "/photos/platforms/suhba-series/suhba-01.jpg", campaign: "Suhba Series — Mother's Day", campaignSlug: "suhba-series", sector: "Owned IPs" },
  { title: "Chaii Republic Unveils Cafe NBO, its New Cultural Tea Hub in Nairobi", url: "https://scholarmedia.africa/hospitality/chaii-republic-unveils-cafe-nbo-new-cultural-tea-hub-in-nairobi/", source: "Scholar Media Africa", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/cafenbo-01", campaign: "Café NBO Opening", campaignSlug: "cafe-nbo", sector: "Hospitality" },
  { title: "Glam Hotel Unveils Chic Rooftop Restaurant and Bar in Nairobi's Westlands", url: "https://newslightkenya.co.ke/glam-hotel-unveils-chic-rooftop-restaurant-and-bar-in-nairobis-westlands/", source: "Newslight Kenya", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/glam-hotel", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Glam Hotel Opens New Rooftop Restaurant and Bar in Nairobi", url: "https://kenyadailymonitor.blogspot.com/2025/11/glam-hotel-opens-new-rooftop-restaurant.html", source: "Kenya Daily Monitor", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/glam-hotel", campaign: "Glam Hotel Rooftop Launch", campaignSlug: "glam-hotel", sector: "Hospitality" },
  { title: "Global beauty brand Allso opens Nairobi flagship store", url: "https://www.the-star.co.ke/news/2026-03-07-global-beauty-brand-opens-nairobi-flagship-store", source: "The Star", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-launch", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Allso launches Nairobi flagship store, marking its official entry into the Kenyan market", url: "https://www.capitalfm.co.ke/news/2026/03/global-beauty-brand-allso-launches-nairobi-flagship-store-marking-its-official-entry-into-the-kenyan-market/", source: "Capital FM", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-l-01", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Global beauty brand Allso opens flagship store in Nairobi CBD", url: "https://www.mpasho.co.ke/lifestyle-yetu/fashion/2026-03-08-global-beauty-brand-allso-opens-flagship-store-in-nairobi-cbd", source: "Mpasho", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-l-02", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Global beauty brand Allso opens flagship store in Nairobi", url: "https://kenyancorporates.co.ke/2026/03/08/global-beauty-brand-allso-opens-flagship-store-in-nairobi/", source: "Kenyan Corporates", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-launch", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Allso: Global beauty giant storms Kenyan market, opens doors in Nairobi", url: "https://mulembe.co.ke/2026/03/08/allso-global-beauty-giant-storms-kenyan-market-opens-doors-in-nairobi/", source: "Mulembe", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-l-01", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Global beauty brand Allso launches Nairobi flagship store", url: "https://hotnews.co.ke/global-beauty-brand-allso-launches-nairobi-flagship-store-marking-its-official-entry-into-the-kenyan-market/", source: "Hot News Kenya", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-l-02", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Global beauty brand Allso enters the Kenyan market", url: "https://newsflash.co.ke/global-beauty-brand-allso-enters-into-the-kenyan-market", source: "Newsflash Kenya", image: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto/FID/allso-launch", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "NTV Trendy Thursday: Glow or gimmick — inside the skincare boom", url: "https://youtu.be/YVDbYbZ97tM", source: "NTV Kenya", image: "https://img.youtube.com/vi/YVDbYbZ97tM/hqdefault.jpg", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "TV47: Allso enters Kenya as a compliant alternative amid unregulated products", url: "https://youtu.be/moj8PZtuPqg", source: "TV47 Kenya", image: "https://img.youtube.com/vi/moj8PZtuPqg/hqdefault.jpg", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
  { title: "Mutembei TV: Inside the Allso flagship store grand opening", url: "https://youtu.be/4u45H_8hsPQ", source: "Mutembei TV", image: "https://img.youtube.com/vi/4u45H_8hsPQ/hqdefault.jpg", campaign: "Allso Beauty Launch", campaignSlug: "allso-beauty", sector: "Beauty, Wellness & Lifestyle" },
];
