import { projects, type Project } from "@/components/lib/projects";
import type { WorkImage, WorkProject } from "@/components/lib/work-types";

const cl = (id: string) =>
  `https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/${id}`;

export const projectGalleryImages: Record<string, WorkImage[]> = {
  "woolworths-kenya": [
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/woolworths-01", label: "Woolworths — Sarit beauty launch" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/woolworths-02", label: "Woolworths — flagship store" },
  ],
  "national-minorities-day": [],
  "africa-urban-forum-2026": [
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/auf-2026", label: "Africa Urban Forum 2026 — KICC" },
    { src: "/photos/projects/africa-urban-forum-2026/auf-n-01.jpg", label: "Africa Urban Forum 2026" },
    { src: "/photos/projects/africa-urban-forum-2026/auf-n-02.jpg", label: "Africa Urban Forum 2026" },
    { src: "/photos/projects/africa-urban-forum-2026/auf-n-03.jpg", label: "Africa Urban Forum 2026" },
    { src: cl("auf-01"), label: "Continental convening" },
    { src: cl("auf-02"), label: "Delegate experience" },
    { src: cl("auf-03"), label: "Stakeholder dialogue" },
  ],
  "utamaduni-day": [],
  "lc-waikiki-africa": [
    { src: "/photos/projects/lc-waikiki/lcw-01.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-02.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-03.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-04.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-05.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-06.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-07.jpg", label: "LC Waikiki — denim campaign" },
    { src: "/photos/projects/lc-waikiki/lcw-08.jpg", label: "LC Waikiki — denim campaign" },
  ],
  "kansai-plascon": [
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/kansai-plascon-launch", label: "Colours of Victory — Gor Mahia launch" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/plascon-01", label: "Plascon brand shoot" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/plascon-b-01", label: "Plascon campaign edit" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-01.jpg", label: "Kansai Plascon — brand shoot" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-02.jpg", label: "Kansai Plascon — brand shoot" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-03.jpg", label: "Kansai Plascon — brand shoot" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-04.jpg", label: "Kansai Plascon — brand shoot" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-05.jpg", label: "Kansai Plascon — brand shoot" },
    { src: "/photos/projects/kansai-plascon-shoot/plascon-s-06.jpg", label: "Kansai Plascon — brand shoot" },
    { src: cl("kansai-01"), label: "Gor Mahia partnership launch" },
    { src: cl("kansai-02"), label: "Colour and community" },
    { src: cl("kansai-03"), label: "Corporate storytelling" },
    { src: cl("kansai-04"), label: "Stakeholder launch" },
    { src: cl("kansai-05"), label: "Brand moment" },
  ],
  "wrc-safari-rally": [
    { src: cl("wrc-01"), label: "WRC Safari Rally — Kenya stage" },
    { src: cl("wrc-02"), label: "WRC Safari Rally — cultural welcome" },
    { src: cl("wrc-03"), label: "WRC Safari Rally — Naivasha at golden hour" },
    { src: cl("wrc-04"), label: "WRC Safari Rally — Kenya stage" },
  ],
  "thrive-hospitality-group": [
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/glam-hotel", label: "Glam Hotel — rooftop launch" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/social8-01", label: "Social 8 — launch entrance" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/chaii-02", label: "Chaii Republic — experience" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/chaii-03", label: "Chaii Republic — brand moment" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/kingfisher-01", label: "Kingfisher Nest — launch" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/kingfisher-02", label: "Kingfisher Nest — hosting" },
    { src: "https://res.cloudinary.com/dnrj0hbpy/image/upload/f_auto,q_auto,w_1800,c_limit/FID/glam-rooftop-01", label: "Glam Hotel — rooftop night" },
    { src: cl("prch-01"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-02"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-03"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-04"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-05"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-06"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-07"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-08"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-09"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-10"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-11"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-12"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-13"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-14"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-15"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-16"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-17"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-18"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-19"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-20"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-21"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-22"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-23"), label: "The Perch at Kingfisher Nest — relaunch" },
    { src: cl("prch-24"), label: "The Perch at Kingfisher Nest — relaunch" },
  ],
  "africa-forum-on-displacements": [],
  "gor-mahia-launch": [
    { src: cl("gor-mahia-01"), label: "Gor Mahia FC — starting XI, CAF Champions League" },
    { src: cl("gm-01"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-02"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-03"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-04"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-05"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-06"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-07"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-08"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-09"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-10"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-11"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-12"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-13"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-14"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-15"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-16"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-17"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-18"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-19"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-20"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-21"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-22"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-23"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
    { src: cl("gm-24"), label: "Kansai Plascon x Gor Mahia — partnership launch" },
  ],
  "gertrudes-foundation": [
    { src: cl("gertrudes-06"), label: "Gertrude's Foundation — mobile clinic outreach" },
    { src: cl("gertrudes-04"), label: "Filming the mobile clinic in the community" },
    { src: cl("gertrudes-01"), label: "On location with the production crew" },
    { src: cl("gertrudes-09"), label: "Community outreach" },
    { src: cl("gertrudes-02"), label: "Mobile clinic day" },
    { src: cl("gertrudes-03"), label: "Gertrude's Foundation" },
    { src: cl("gertrudes-05"), label: "Gertrude's Foundation" },
    { src: cl("gertrudes-07"), label: "Gertrude's Foundation" },
    { src: cl("gertrudes-08"), label: "Gertrude's Foundation" },
    { src: cl("gertrudes-10"), label: "Gertrude's Foundation" },
  ],
  "columbia-africa-healthcare": [
    { src: "/photos/projects/columbia/columbia-01.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-02.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-03.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-04.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-05.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-06.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-07.jpg", label: "Columbia Africa Healthcare" },
    { src: "/photos/projects/columbia/columbia-08.jpg", label: "Columbia Africa Healthcare" },
  ],
  "medigah-london-hair": [
    { src: "/photos/projects/medigah/mlh-01.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-02.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-03.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-04.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-05.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-06.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-07.jpg", label: "Medigah London Hair — MLH app launch" },
    { src: "/photos/projects/medigah/mlh-08.jpg", label: "Medigah London Hair — MLH app launch" },
  ],
  "allso-beauty": [
    { src: "/photos/projects/allso-beauty/allso-l-01.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-02.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-03.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-04.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-05.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-06.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-07.jpg", label: "Allso Beauty — launch" },
    { src: "/photos/projects/allso-beauty/allso-l-08.jpg", label: "Allso Beauty — launch" },
    { src: cl("allso-01"), label: "Launch event atmosphere" },
    { src: cl("allso-02"), label: "Beauty creator engagement" },
    { src: cl("allso-03"), label: "Influencer storytelling" },
    { src: cl("allso-04"), label: "Brand moment" },
    { src: cl("allso-05"), label: "Digital amplification" },
    { src: cl("als-01"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-02"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-03"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-04"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-05"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-06"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-07"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-08"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-09"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-10"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-11"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-12"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-13"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-14"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-15"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-16"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-17"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-18"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-19"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-20"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-21"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-22"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-23"), label: "Allso Beauty — Nairobi flagship launch" },
    { src: cl("als-24"), label: "Allso Beauty — Nairobi flagship launch" },
  ],
};

export function getProjectGallery(project: Pick<Project, "slug" | "title">): WorkImage[] {
  return projectGalleryImages[project.slug] ?? [];
}

export function toWorkProject(project: Project): WorkProject {
  return {
    ...project,
    tagline: project.desc,
    color: undefined,
    images: getProjectGallery(project),
  } as WorkProject;
}

export const workProjects = projects.map(toWorkProject);
