// One-off: fetch curated, on-brand stock photos from Pexels and write their
// CDN URLs to lib/stock-photos.ts. Run: node scripts/fetch-pexels.mjs
import fs from "node:fs";

const KEY = (fs.readFileSync(".env.local", "utf8").match(/PEXELS_API_KEY=(.+)/) || [])[1]?.trim();
if (!KEY) { console.error("No PEXELS_API_KEY in .env.local"); process.exit(1); }

// key -> specific, on-brand search term (per creative-direction.md)
const QUERIES = {
  about:        "african business meeting",
  pressConf:    "corporate press conference",
  media:        "television studio interview",
  digital:      "content creator filming phone",
  experiential: "concert stage lights crowd",
  strategy:     "strategy whiteboard meeting",
  government:   "conference summit speaker podium",
  corporate:    "corporate boardroom executives",
  hospitality:  "restaurant interior ambient",
  beauty:       "beauty editorial studio portrait",
};

const pick = (p) => ({
  src: p.src.large2x,
  thumb: p.src.large,
  w: p.width, h: p.height,
  alt: p.alt || "",
  photographer: p.photographer,
  url: p.url,
});

const out = {};
for (const [k, q] of Object.entries(QUERIES)) {
  const r = await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(q)}&per_page=4&orientation=landscape`, {
    headers: { Authorization: KEY },
  });
  if (!r.ok) { console.error(k, r.status, await r.text()); continue; }
  const j = await r.json();
  out[k] = (j.photos || []).map(pick);
  console.log(k, "→", out[k].length, "photos");
}

const header = `// AUTO-GENERATED by scripts/fetch-pexels.mjs — curated Pexels stock (free, no attribution required).\n// Re-run the script to refresh. Photographer credits retained in metadata.\n\n`;
const body =
  `export type StockPhoto = { src: string; thumb: string; w: number; h: number; alt: string; photographer: string; url: string };\n\n` +
  `export const STOCK: Record<string, StockPhoto[]> = ${JSON.stringify(out, null, 2)};\n\n` +
  `export const stock = (key: string, i = 0): StockPhoto | undefined => STOCK[key]?.[i];\n`;

fs.mkdirSync("lib", { recursive: true });
fs.writeFileSync("lib/stock-photos.ts", header + body);
console.log("wrote lib/stock-photos.ts");
