// AUTO-GENERATED by scripts/fetch-pexels.mjs — curated Pexels stock (free, no attribution required).
// Re-run the script to refresh. Photographer credits retained in metadata.

export type StockPhoto = { src: string; thumb: string; w: number; h: number; alt: string; photographer: string; url: string };

export const STOCK: Record<string, StockPhoto[]> = {
  "about": [
    {
      "src": "https://images.pexels.com/photos/30688593/pexels-photo-30688593.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/30688593/pexels-photo-30688593.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 4080,
      "h": 2720,
      "alt": "Group of professionals having a casual meeting in an office setting in Lagos.",
      "photographer": "Ninthgrid",
      "url": "https://www.pexels.com/photo/casual-office-meeting-in-lagos-nigeria-30688593/"
    },
    {
      "src": "https://images.pexels.com/photos/7640793/pexels-photo-7640793.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7640793/pexels-photo-7640793.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "An office meeting where a man argues with a woman over documents, causing tension.",
      "photographer": "Yan Krukau",
      "url": "https://www.pexels.com/photo/a-man-scolding-a-woman-sitting-at-a-desk-7640793/"
    },
    {
      "src": "https://images.pexels.com/photos/8761679/pexels-photo-8761679.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/8761679/pexels-photo-8761679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5473,
      "h": 3654,
      "alt": "Three business professionals smiling at a corporate event, wearing formal attire and badges.",
      "photographer": "Pavel Danilyuk",
      "url": "https://www.pexels.com/photo/a-woman-standing-between-two-men-8761679/"
    },
    {
      "src": "https://images.pexels.com/photos/9301257/pexels-photo-9301257.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/9301257/pexels-photo-9301257.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "A diverse team engaging in a business presentation in a modern office setting.",
      "photographer": "Mikhail Nilov",
      "url": "https://www.pexels.com/photo/a-man-making-a-business-presentation-to-colleagues-9301257/"
    }
  ],
  "pressConf": [
    {
      "src": "https://images.pexels.com/photos/6950236/pexels-photo-6950236.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950236/pexels-photo-6950236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6720,
      "h": 4402,
      "alt": "Journalists conduct an interview with a senior executive in a formal office setting.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/an-elderly-man-having-an-interview-6950236/"
    },
    {
      "src": "https://images.pexels.com/photos/6950208/pexels-photo-6950208.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950208/pexels-photo-6950208.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6573,
      "h": 4382,
      "alt": "Three business professionals giving a speech with an American flag backdrop.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/an-elderly-man-having-a-speech-in-front-of-the-microphone-of-a-podium-6950208/"
    },
    {
      "src": "https://images.pexels.com/photos/6950229/pexels-photo-6950229.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950229/pexels-photo-6950229.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5200,
      "h": 3467,
      "alt": "A journalist interviews a businessman in a conference room, capturing a professional and political setting.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/television-reporter-in-front-of-a-conference-room-6950229/"
    },
    {
      "src": "https://images.pexels.com/photos/6950232/pexels-photo-6950232.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950232/pexels-photo-6950232.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5200,
      "h": 3467,
      "alt": "Confident businessman answering questions from the media during a press conference indoors.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/a-man-in-black-suit-having-an-interview-6950232/"
    }
  ],
  "media": [
    {
      "src": "https://images.pexels.com/photos/18357250/pexels-photo-18357250.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/18357250/pexels-photo-18357250.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Capture of a video interview scene with professional camera equipment.",
      "photographer": "Isaiah Ekele",
      "url": "https://www.pexels.com/photo/close-up-of-a-camcorder-18357250/"
    },
    {
      "src": "https://images.pexels.com/photos/35755251/pexels-photo-35755251.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/35755251/pexels-photo-35755251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 3078,
      "h": 2048,
      "alt": "A professional interview in a luxurious, historical room with rich decor and art.",
      "photographer": "Jitte Davidson",
      "url": "https://www.pexels.com/photo/interview-in-elegant-historical-interior-setting-35755251/"
    },
    {
      "src": "https://images.pexels.com/photos/31656366/pexels-photo-31656366.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/31656366/pexels-photo-31656366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Camera capturing an indoor interview scene, in focus with a blurred background.",
      "photographer": "Caique Araujo",
      "url": "https://www.pexels.com/photo/black-and-white-behind-the-scenes-filming-31656366/"
    },
    {
      "src": "https://images.pexels.com/photos/2041396/pexels-photo-2041396.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/2041396/pexels-photo-2041396.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Woman being recorded in a professional studio setup, using video camera and lighting equipment.",
      "photographer": "CoWomen",
      "url": "https://www.pexels.com/photo/black-video-camera-2041396/"
    }
  ],
  "digital": [
    {
      "src": "https://images.pexels.com/photos/8360497/pexels-photo-8360497.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/8360497/pexels-photo-8360497.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6720,
      "h": 4480,
      "alt": "Man filming creative content with smartphone on gimbal indoors.",
      "photographer": "Ron Lach",
      "url": "https://www.pexels.com/photo/man-filming-himself-using-a-smartphone-8360497/"
    },
    {
      "src": "https://images.pexels.com/photos/7243099/pexels-photo-7243099.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7243099/pexels-photo-7243099.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Young ethnic female vlogger with curly hair in jacket preparing cellphone for video record in town",
      "photographer": "Blue Bird",
      "url": "https://www.pexels.com/photo/ethnic-blogger-with-smartphone-on-city-street-7243099/"
    },
    {
      "src": "https://images.pexels.com/photos/8371123/pexels-photo-8371123.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/8371123/pexels-photo-8371123.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6720,
      "h": 4480,
      "alt": "Tattooed woman with blonde hair adjusts smartphone on tripod for vlog setup indoors.",
      "photographer": "Ron Lach",
      "url": "https://www.pexels.com/photo/a-tattooed-woman-using-a-smartphone-8371123/"
    },
    {
      "src": "https://images.pexels.com/photos/8360444/pexels-photo-8360444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/8360444/pexels-photo-8360444.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6720,
      "h": 4480,
      "alt": "A young man recording video content indoors with a smartphone and tripod.",
      "photographer": "Ron Lach",
      "url": "https://www.pexels.com/photo/a-man-creating-video-content-8360444/"
    }
  ],
  "experiential": [
    {
      "src": "https://images.pexels.com/photos/13230484/pexels-photo-13230484.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/13230484/pexels-photo-13230484.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5081,
      "h": 3811,
      "alt": "Night concert scene with audience, stage, and colorful lighting effects.",
      "photographer": "Lisa from Pexels",
      "url": "https://www.pexels.com/photo/crowd-of-people-at-a-concert-13230484/"
    },
    {
      "src": "https://images.pexels.com/photos/5193526/pexels-photo-5193526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/5193526/pexels-photo-5193526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5419,
      "h": 3613,
      "alt": "A large outdoor concert audience enjoying a live music event with vibrant lights at night.",
      "photographer": "Maor Attias",
      "url": "https://www.pexels.com/photo/people-watching-live-concert-5193526/"
    },
    {
      "src": "https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5043,
      "h": 3362,
      "alt": "Energetic live music concert featuring performers on a vibrant stage, captivating a large audience.",
      "photographer": "george charry",
      "url": "https://www.pexels.com/photo/crowd-watching-on-a-live-concert-4218027/"
    },
    {
      "src": "https://images.pexels.com/photos/167605/pexels-photo-167605.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/167605/pexels-photo-167605.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 4928,
      "h": 3264,
      "alt": "Dynamic live concert with band on stage, lighting effects, and enthusiastic crowd at night.",
      "photographer": "Thibault Trillet",
      "url": "https://www.pexels.com/photo/photo-of-concert-band-during-night-time-167605/"
    }
  ],
  "strategy": [
    {
      "src": "https://images.pexels.com/photos/5439481/pexels-photo-5439481.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/5439481/pexels-photo-5439481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5605,
      "h": 3737,
      "alt": "Multicultural team discussing strategies in a conference room with a whiteboard presentation.",
      "photographer": "Tima Miroshnichenko",
      "url": "https://www.pexels.com/photo/coworkers-in-a-conference-room-having-a-meeting-5439481/"
    },
    {
      "src": "https://images.pexels.com/photos/7964146/pexels-photo-7964146.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7964146/pexels-photo-7964146.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Business professionals engaging in a collaborative meeting using a whiteboard for brainstorming.",
      "photographer": "Felicity Tai",
      "url": "https://www.pexels.com/photo/employees-on-a-conference-room-7964146/"
    },
    {
      "src": "https://images.pexels.com/photos/7698706/pexels-photo-7698706.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7698706/pexels-photo-7698706.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6000,
      "h": 4000,
      "alt": "Two colleagues in formal attire discussing strategies on a whiteboard in a modern office space.",
      "photographer": "Yan Krukau",
      "url": "https://www.pexels.com/photo/man-and-woman-writing-on-the-whiteboard-7698706/"
    },
    {
      "src": "https://images.pexels.com/photos/7989092/pexels-photo-7989092.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7989092/pexels-photo-7989092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6016,
      "h": 4016,
      "alt": "Business professional drawing graph during office presentation with colleague",
      "photographer": "Mikhail Nilov",
      "url": "https://www.pexels.com/photo/a-person-in-smart-casual-attire-drawing-on-a-whiteboard-7989092/"
    }
  ],
  "government": [
    {
      "src": "https://images.pexels.com/photos/6949938/pexels-photo-6949938.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6949938/pexels-photo-6949938.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6720,
      "h": 4480,
      "alt": "Diverse group of professionals in a formal meeting setting with a speaker at the podium.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/elderly-woman-talking-in-front-of-people-on-a-conference-room-6949938/"
    },
    {
      "src": "https://images.pexels.com/photos/6949931/pexels-photo-6949931.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6949931/pexels-photo-6949931.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6618,
      "h": 4412,
      "alt": "Formal business meeting with a diverse group and speaker at a podium in a conference room.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/man-in-black-suit-standing-in-front-of-black-laptop-computer-6949931/"
    },
    {
      "src": "https://images.pexels.com/photos/6950206/pexels-photo-6950206.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950206/pexels-photo-6950206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6514,
      "h": 4343,
      "alt": "A diverse team in business attire at a podium with an American flag, showing unity and professionalism.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/men-in-business-attire-looking-at-the-woman-talking-near-the-podium-6950206/"
    },
    {
      "src": "https://images.pexels.com/photos/6950158/pexels-photo-6950158.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950158/pexels-photo-6950158.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5200,
      "h": 3467,
      "alt": "A woman giving a speech at a podium with an EU flag in a conference setting.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/a-woman-near-the-podium-having-a-speech-6950158/"
    }
  ],
  "corporate": [
    {
      "src": "https://images.pexels.com/photos/7433840/pexels-photo-7433840.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7433840/pexels-photo-7433840.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6521,
      "h": 4347,
      "alt": "Business professionals discussing documents in a modern meeting room.",
      "photographer": "Vlada Karpovich",
      "url": "https://www.pexels.com/photo/a-group-of-people-discussing-in-a-room-7433840/"
    },
    {
      "src": "https://images.pexels.com/photos/7433919/pexels-photo-7433919.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7433919/pexels-photo-7433919.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6632,
      "h": 4421,
      "alt": "Three mature professionals in a business meeting discussing and signing documents in an office setting.",
      "photographer": "Vlada Karpovich",
      "url": "https://www.pexels.com/photo/gray-haired-man-signing-the-papers-7433919/"
    },
    {
      "src": "https://images.pexels.com/photos/6950048/pexels-photo-6950048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/6950048/pexels-photo-6950048.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 6586,
      "h": 4391,
      "alt": "Business professionals engaging in a meeting in a modern conference room.",
      "photographer": "Werner Pfennig",
      "url": "https://www.pexels.com/photo/men-in-suit-jackets-standing-in-front-a-person-in-gray-plaid-jacket-6950048/"
    },
    {
      "src": "https://images.pexels.com/photos/7433847/pexels-photo-7433847.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/7433847/pexels-photo-7433847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5755,
      "h": 3837,
      "alt": "Business professionals engaged in a collaborative meeting around a conference table.",
      "photographer": "Vlada Karpovich",
      "url": "https://www.pexels.com/photo/people-having-a-meeting-7433847/"
    }
  ],
  "hospitality": [
    {
      "src": "https://images.pexels.com/photos/32568165/pexels-photo-32568165.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/32568165/pexels-photo-32568165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5397,
      "h": 4048,
      "alt": "Elegant indoor restaurant setting with wooden furniture, warm lighting, and decorative foliage.",
      "photographer": "Magda Ehlers",
      "url": "https://www.pexels.com/photo/charming-indoor-restaurant-with-elegant-decor-32568165/"
    },
    {
      "src": "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 4608,
      "h": 2592,
      "alt": "A sophisticated restaurant interior with elegant table setting and ambient candlelight, creating a cozy atmosphere.",
      "photographer": "Chan Walrus",
      "url": "https://www.pexels.com/photo/wine-glasses-on-table-tops-941861/"
    },
    {
      "src": "https://images.pexels.com/photos/10918163/pexels-photo-10918163.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/10918163/pexels-photo-10918163.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5409,
      "h": 3606,
      "alt": "Cozy restaurant interior with wooden seating and vibrant neon lights creating a warm ambiance.",
      "photographer": "Deybson Mallony",
      "url": "https://www.pexels.com/photo/brown-table-with-chairs-in-the-restaurant-10918163/"
    },
    {
      "src": "https://images.pexels.com/photos/9438971/pexels-photo-9438971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/9438971/pexels-photo-9438971.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 4697,
      "h": 3823,
      "alt": "Inviting restaurant interior overlooking cityscape in Cluj-Napoca, perfect for dining with a view.",
      "photographer": "Gabriel Bulz",
      "url": "https://www.pexels.com/photo/brown-wooden-round-table-with-chairs-beside-a-glass-window-9438971/"
    }
  ],
  "beauty": [
    {
      "src": "https://images.pexels.com/photos/14195374/pexels-photo-14195374.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/14195374/pexels-photo-14195374.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5472,
      "h": 3648,
      "alt": "Close-up portrait of a woman with striking makeup and elegant pose.",
      "photographer": "shahin khalaji",
      "url": "https://www.pexels.com/photo/close-up-photo-of-woman-wearing-makeup-14195374/"
    },
    {
      "src": "https://images.pexels.com/photos/14030970/pexels-photo-14030970.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/14030970/pexels-photo-14030970.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 2730,
      "h": 1820,
      "alt": "Studio portrait of a woman with dark hair and thoughtful expression, showcasing elegance and fashion.",
      "photographer": "Pegah Sharifi",
      "url": "https://www.pexels.com/photo/portrait-of-beautiful-brunette-woman-14030970/"
    },
    {
      "src": "https://images.pexels.com/photos/20210083/pexels-photo-20210083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/20210083/pexels-photo-20210083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5568,
      "h": 3712,
      "alt": "Fashion portrait of a woman in leopard print blouse, arms raised, with bold makeup on red background.",
      "photographer": "Alessandra Shalbe",
      "url": "https://www.pexels.com/photo/blonde-woman-with-arms-raised-20210083/"
    },
    {
      "src": "https://images.pexels.com/photos/20210091/pexels-photo-20210091.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "thumb": "https://images.pexels.com/photos/20210091/pexels-photo-20210091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      "w": 5568,
      "h": 3712,
      "alt": "Studio portrait featuring a stylish model with a bold look and red background.",
      "photographer": "Alessandra Shalbe",
      "url": "https://www.pexels.com/photo/blonde-with-glamour-makeup-20210091/"
    }
  ]
};

export const stock = (key: string, i = 0): StockPhoto | undefined => STOCK[key]?.[i];
